#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

## Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

## Elixir Config

export ERL_AFLAGS="-kernel shell_history enabled"

## Open in existing emacs session

alias eclient='emacsclient --alternate-editor="" --no-wait $*' #quotes intentionaly left blan

## Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

## Tell ls to be colourful

export CLICOLOR=1

export LSCOLORS=Exfxcxdxbxegedabagacad

## Support 256 colors, even over SSH

export TERM='xterm-256color'

export LANG=en_US.UTF-8

## Build $PATH

export PATH="$PATH:/usr/local/bin/ruby"

export PATH="$PATH:/Users/nzeltzer/.rvm/gems/ruby-2.5.1/bin"

export PATH="$PATH:$HOME/.rvm/bin"

export PATH="$PATH:/Users/nzeltzer/Software/ruby/bin"

export PATH="$PATH:/usr/local/bin"

export PATH="$PATH:/usr/local/bin/mosh-server"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

## RVM (must be sourc)

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*