#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.fonts/*.sh

POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon ssh dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)

export PATH="$PATH:/usr/local/bin/ruby"

export PATH="$PATH:/Users/nzeltzer/.rvm/gems/ruby-2.5.1/bin"

export PATH="$PATH:$HOME/.rvm/bin"

export PATH="$PATH:/Users/nzeltzer/Software/ruby/bin"

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
